config/routes.rb
Rails.application.routes.draw do
  get 'ver_video/index'

  get 'codigo_postal/:cp', to: 'codigo_postal#index'
  get 'credits/nuevo', to:'credits#nuevo' 

  get 'combos/pais'

  get 'combos/estado'

  get 'combos/ciudad'
  get 'customers/:id/historial',to:'customers#historial',as:'customer_historial'
  get 'reports/seguimiento'
  get 'reports/clientes'
  get 'reports/historial_de_recibos'
  get 'reports/seguimiento_quincenal'
  get 'reports/num_tablero'
  get 'reports/vencidos'
  get 'reports/cobranza'
  get 'reports/pronostico_de_cobranza'
  get 'reports/reporte_de_pagos'
  get 'reports/estado_de_cuenta'
  get 'reports/calificaciones'
  get 'reports/historial_de_pagos'
  get 'reports/usuarios'
  get 'reports/agentes'
  get 'reports/dtkta'
  get 'reports/dtkta_cuentas'
  get 'reports/dtkta_perfil'
  get 'reports/dtkta_movtos'
  get 'multiprint',to:"tickets#multiprint" ,as: "multiprint"
  put 'cancelar/:id', to:'tickets#cancelar', as: "cancelar"
  get 'reports/consulta_creditos'

  post 'credit/cancelar/:id', to: 'credits#cancelar', as: "cancelar_credito"
  resources :tickets
  resources :destinations
  resources :payments
  get 'payments/:id/vencer', to:'payments#vencer' 
  get 'payments/:id/pagar', to:'payments#pagar'
  get 'paymentscompany', to:'payments#paymentscompany', as:'paymentscompany'
  resources :receipts

  get 'receipts/crear'

  get 'receipts/baja'
  get '/pdf/:id', to: 'credits#pdf', as: 'pdf'
  get '/text/:id', to: 'credits#text', as: 'text'
  resources :confs , except:[:new,:create,:index,:delete]
  get 'test/t21'
  get 'view_credits/documentos',to:'view_credits#documentos'
  get 'view_credits/autorizacion',to:'view_credits#autorizacion'
  get 'view_credits/caratula',to:'view_credits#caratula'
  get 'view_credits/disposiciones',to:'view_credits#disposiciones'
  get 'view_credits/caratulamun',to:'view_credits#caratulamun'
  get 'view_credits/corrida',to:'view_credits#corrida'
  get 'view_credits/corridamun',to:'view_credits#corridamun'
  get 'view_credits/contrato',to:'view_credits#contrato'
  get 'view_credits/contratomunicipal',to:'view_credits#contratomunicipal'
  get 'view_credits/entrevista',to:'view_credits#entrevista'
  get 'view_credits/poliza',to:'view_credits#poliza'
  get 'view_credits/polizamun',to:'view_credits#polizamun'
  
  get 'view_credits',to:'view_credits#index',as:'view_credits'
  get 'view_credits/aceptadas',to:'view_credits#aceptadas',as:'view_credits_aceptadas'
  get 'view_credits/rechazadas',to:'view_credits#rechazadas',as:'view_credits_rechazadas'
  resources :view_credits
  
  resources :customers
  get 'credits/:id/editpdf', to:'credits#editpdf',as:'editpdf'
  get 'view_credits/:id/pagos', to:'view_credits#pagos',as:'creditpagos'
  resources :credits
  resources :payouts
  resources :loans
  resources :products
  devise_for :users
  resources :agents
  resources :companies
  resources :branch_offices
  resources :users
  get 'perfil',to:'users#perfil',as:'perfil'
  get 'users/edit_pass/:id',to:'users#edit_pass', as: "edit_pass"
   post 'users/create2',to:'users#create2'
  
  devise_for :models
  get 'welcome/hola'

  

  root 'welcome#hola'

end

app/controllers/view_credits_controller.rb
class ViewCreditsController < ApplicationController
   before_action :set_credit, only: [:autorizacion,:caratula,:disposiciones,:caratulamun,:contratomunicipal,:contrato,:entrevista,:poliza,:polizamun,:corrida,:corridamun,:documentos, :getFecha]
  before_action :set_credits, only:[:show, :edit, :update, :destroy]
 
  def index
    @credits = Credit.all.where(status:0).select(:id,:fecha,:apellido_paterno,:apellido_materno,:nombre_1,:nombre_2,:RFC,:fecha_de_contrato,:monto_solicitud,:agente_empresa,:referencia_agente_empresa,:created_at).order(:created_at)
    if current_user.tipo==3
      @credits= Credit.get_by_branch_office(@credits,current_user.branchOffices[0])
    end
  end
  def aceptadas
  end
  def rechazadas
    @credits = Credit.all.where(status:2).select(:id,:fecha,:apellido_paterno,:apellido_materno,:nombre_1,:nombre_2,:RFC,:fecha_de_contrato,:monto_solicitud,:agente_empresa,:referencia_agente_empresa)
    if current_user.tipo==3
       @credits= Credit.get_by_branch_office(@credits,current_user.branchOffices[0])
    end
  end
  # GET /credits/1
  # GET /credits/1.json
  def show
  end
  
  def documentos
    @link =  (params[:retorno] == "1") ? "/view_credits/aceptadas" : "/customers/#{@credit.customer_id}/historial"
  end
  def pagos
    @credit = Credit.find(params[:id])
    @payments = Payment.joins(:credit).where("credits.id = ?",@credit.id).order(:created_at)
  end
  def autorizacion
    pdf = AutorizacionPdf.new(@credit)
    send_data pdf.render, filename: 'report.pdf', type: 'application/pdf', disposition: "inline"
    #filename = "#{Rails.root}/app/pdf/autorizacion_en_blanco.pdf"
    #Prawn::Document.generate("full_template.pdf", :template => filename) do
    #  text "THis content is written on the first page of the template", :align => :center
    #end
  end
  def caratula
    pdf = CaratulaPdf.new(@credit)
    send_data pdf.render, filename: 'report.pdf', type: 'application/pdf', disposition: "inline"
  end
  
  def caratulamun
    pdf = CaratulamunPdf.new(@credit)
    send_data pdf.render, filename: 'report.pdf', type: 'application/pdf', disposition: "inline"
  end

  def disposiciones
    pdf = DisposicionesPdf.new(@credit)
    send_data pdf.render, filename: 'report.pdf', type: 'application/pdf', disposition: "inline"
  end
  
  def contratomunicipal
    if (@credit.fecha_de_contrato.nil?)
      @credit.update(fecha_de_contrato:Time.now)
    end
    if @credit.payments.count==0
      getArreglomun()
      n = 0
      @datos.each do |d|
        n += 1
        payment_v = Payment.create(fecha_de_pago:d[1],recibo:"#{n}/#{@datos.count}",estatus:0,importe:d[8],credit:@credit, pago:0, interes:0,fecha_de_corte:d[9],fecha_de_impresion:d[10])
        payment_v.delay(run_at:d[8]).cargar_interes
      end
    end
    
    #pdf= Prawn:: Document.new(@credit)
    pdf = ContratoMunicipalPdf.new(@credit)
    send_data pdf.render, filename: 'report.pdf', type: 'application/pdf', disposition: "inline"
  end
  
  def contrato
    if (@credit.fecha_de_contrato.nil?)
      @credit.update(fecha_de_contrato:Time.now)
    end
    if @credit.payments.count==0
      getArreglo()
      n = 0
      @datos.each do |d|
        n += 1
        payment_v = Payment.create(fecha_de_pago:d[1],recibo:"#{n}/#{@datos.count}",estatus:0,importe:d[6],credit:@credit, pago:0, interes:0,fecha_de_corte:d[8],fecha_de_impresion:d[9])
        payment_v.delay(run_at:d[8]).cargar_interes
      end
    end
      
    pdf = ContratoPdf.new(@credit)
     
    send_data pdf.render, filename: 'report.pdf', type: 'application/pdf', disposition: "inline"
  end
  def entrevista
    pdf = EntrevistaPdf.new(@credit)
    send_data pdf.render, filename: 'report.pdf', type: 'application/pdf', disposition: "inline"
  end
  def poliza
    pdf = PolizaPdf.new(@credit)
    send_data pdf.render, filename: 'report.pdf', type: 'application/pdf', disposition: "inline"
  end
  
  def polizamun
    pdf = PolizamunPdf.new(@credit)
    send_data pdf.render, filename: 'report.pdf', type: 'application/pdf', disposition: "inline"
  end
  
  def corrida
    getArreglo()
    pdf = CorridaPdf.new(@credit,@arreglo)
    send_data pdf.render, filename: 'report.pdf', type: 'application/pdf', disposition: "inline"
  end
  
  def corridamun
    getArreglomun()
    pdf = CorridamunPdf.new(@credit,@arreglomun)
    send_data pdf.render, filename: 'report.pdf', type: 'application/pdf', disposition: "inline"
  end
  
  
   def inferior(val,array)
      array.sort!
      array.reverse!
      array.each do |n|                                                                                                                                                                                                                   
        return n.to_i if val.to_i > n.to_i
      end
      return val.to_i
   end
   
   
  def getArreglo
     if (@credit.fecha_de_contrato.nil?)
      fecha = Time.now.to_date
    else
      fecha = @credit.fecha_de_contrato.to_date
    end
    
    cantidad= @credit.product.payout.getDays.length
    fin_mes= @credit.product.payout.getDays.include? "-1"
    dias=  @credit.product.payout.getDays - ["-1"]
    cortes =  @credit.product.payout.getFlow.sort!
    dias_int =[]
    cortes_int = []
    dias.each do |i|
      dias_int.push(i.to_i)
    end
    dias_int.sort!
    dias.push("-1") if fin_mes
    dia_inicial = nil;
    cortes.each do |i |
      cortes_int.push(i.to_i)
    end
    cortes_int.sort!
      cont = 0
      dias.each do |dia|
         dia= fecha.end_of_month.day if dia=="-1"
         if fecha.day<dia.to_i
           if fecha.day <inferior(dia,cortes_int)
            dia_inicial=cont
            puts "dia #{dia}"
            break
           end
         end
         cont +=1
      end
        
        if dia_inicial==nil
          dia_inicial = 0
        end
        puts "dia inicial #{dia_inicial}"
        puts dias

    @total= @credit.monto_solicitud.to_f + (@credit.monto_solicitud.to_f * (@credit.taza_ord/100))
    @pago = @total/@credit.product.numero_de_pagos_a_realizar
    @capital = @pago/(1 + (@credit.taza_ord / 100))
    #@interes = (@capital * ( @credit.product.taza_de_interes_ordinaria / 100))/ (1+ ((@credit.product.taza_de_interes_ordinaria - @credit.product.cat_sin_iva)/ 100))
    @interes = (@capital * ((@credit.taza_ord / 100) / 1.16))
    #if @credit.product.comision_apert >0
      #@interes = (@capital * ((@credit.product.taza_de_interes_ordinaria / 100)))
      #@iva = @interes*(16/100)
    #else
      @interes = (@capital * ((@credit.taza_ord / 100) / 1.16))
      @iva = @interes*(16)/100
      ##@iva = @interes * (16/100)
    #end
    #@iva = @interes*(@credit.product.taza_de_interes_ordinaria - @credit.product.cat_sin_iva)/100
    
    #@com_apert = (@capital + @interes) * (@credit.product.comision_apert / 100) 
    @datos = []
    @arreglo = []
    @arreglo.push(["PERIODO", "FECHA DE PAGO", "SALDO INICIAL", "CAPITAL", "INTERES", "IVA DE INTERES","PAGO TOTAL", "SALDO FINAL"])
    puts "=========================================================================================================================================="
    @credit.product.numero_de_pagos_a_realizar.times do |n|
        
        aux= getFecha(dias,dia_inicial,n,fecha,cortes_int)
        fecha = aux["pago"]
        fecha_de_corte = aux["corte"]
        fecha_de_impresion = aux["impresion"]
     
      puts fecha
      puts fecha_de_corte
      puts fecha_de_impresion  
      #              1   2                         4       5          6      7           8                       9                 10            
      @datos.push([n+1,fecha,(@total-((n)*@pago)),@capital,@interes,@iva,@pago,((@total-((n)*@pago))-@pago),fecha_de_corte,fecha_de_impresion])
      #@datos.push([n+1,fecha,(@total-((n)*@pago)),@capital,@interes,@iva,@com_apert,@pago,((@total-((n)*@pago))-@pago),fecha_de_corte,fecha_de_impresion])
      @arreglo.push([ "#{n+1}",fecha.to_date.strftime("%d-%m-%Y"),"#{Dinero.to_money((@total-((n)*@pago)).round(2))}","#{Dinero.to_money(@capital.round(2))}","#{Dinero.to_money(@interes.round(2))}","#{Dinero.to_money(@iva.round(2))}","#{Dinero.to_money(@pago.round(2))}","#{Dinero.to_money(((@total-((n)*@pago))-@pago).round(2))}"])
      #@arreglo.push([ "#{n+1}",fecha.to_date.strftime("%d-%m-%Y"),"#{Dinero.to_money((@total-((n)*@pago)).round(2))}","#{Dinero.to_money(@capital.round(2))}","#{Dinero.to_money(@interes.round(2))}","#{Dinero.to_money(@iva.round(2))}","#{Dinero.to_money(@com_apert.round(2))}","#{Dinero.to_money(@pago.round(2))}","#{Dinero.to_money(((@total-((n)*@pago))-@pago).round(2))}"])
    end
    puts "=========================================================================================================================================="
  end
  
  
  def getArreglomun
     if (@credit.fecha_de_contrato.nil?)
      fecha = Time.now.to_date
    else
      fecha = @credit.fecha_de_contrato.to_date
    end
    cantidad= @credit.product.payout.getDays.length
    fin_mes= @credit.product.payout.getDays.include? "-1"
    dias=  @credit.product.payout.getDays - ["-1"]
    cortes =  @credit.product.payout.getFlow.sort!
    dias_int =[]
    cortes_int = []
    dias.each do |i|
      dias_int.push(i.to_i)
    end
    dias_int.sort!
    dias.push("-1") if fin_mes
    dia_inicial = nil;
    cortes.each do |i |
      cortes_int.push(i.to_i)
    end
    cortes_int.sort!
      cont = 0
      dias.each do |dia|
         dia= fecha.end_of_month.day if dia=="-1"
         if fecha.day<dia.to_i
           if fecha.day <inferior(dia,cortes_int)
            dia_inicial=cont
            puts "dia #{dia}"
            break
           end
         end
         cont +=1
      end
        
        if dia_inicial==nil
          dia_inicial = 0
        end
        puts "dia inicial #{dia_inicial}"
        puts dias
    #@total= @credit.monto_solicitud.to_f + (@credit.monto_solicitud.to_f * (@credit.product.taza_de_interes_ordinaria/100))

app/helpers/view_credit_helper.rb
module ViewCreditHelper
end

app/views/view_credits/corrida.html.erb
<p id="notice"><%= notice %></p>

<h1></h1>

<table>
  <thead>
    <tr>
      <th>Periodo</th>
      <th>Fecha de pago</th>
      <th>Saldo inicial</th>
      <th>Capital</th>
      <th>Interés</th>
      <th>Iva interés</th>
      <th>Pago total</th>
      <th>Saldo final</th>
    </tr>
  </thead>
  <%fecha = @credit.fecha%>
  <tbody>
    <% @credit.product.numero_de_pagos_a_realizar.times do |n| %>
      <tr>
        <td><%= n+1 %></td>
         <% unless (n%2==1)%>
          <td><%=fecha=fecha.end_of_month%></td>
        <%else%>
          <td><%=fecha=fecha+15.day %></td>
        <%end%>
        <td><%= (@total-((n)*@pago)) %></td>
        <td><%= @capital %></td>
        <td><%= @interes %></td>
        <td><%= @iva %></td>
        <td><%= @pago %></td>
        <td><%= (@total-((n)*@pago))-@pago %></td>
      </tr>
    <% end %>
  </tbody>
</table>
n, @credit.fecha, (total-((n-1)*pago)),capital,interes,iva,pago,"hola" 
<br>

app/views/view_credits/index.html.erb
<p id="notice"><%= notice %></p>

<h2 align="center">SOLICITUDES DE CREDITOS POR ACEPTAR</h2>
<style>
  td{
    padding:5px 5px; 
  }
</style >
<table style="font-size:12px;">
  <thead>
    <tr>
      <th>AGENTE/EMPRESA</th>
      <th>SUCURSAL</th>
      <th>FECHA</th>
      <th>NOMBRE</th>
      <th>RFC</th>
      <th>MONTO</th>
      <th>CREACION</th>
      <th colspan="4"></th>
    </tr>
  </thead>


  <tbody>
    <% @credits.each do |credit| %>
      <tr>
        <%if credit.agente_empresa %>
          <td><%= credit.padre.nombre_completo%></td>
        <%else%>
          <td><%= credit.padre.nombre_completo%></td>
        <%end%>
        <td><%= credit.padre.branch_office.nombre%></td>
        <td><%= credit.fecha.strftime("%d/%m/%Y") %></td>
        <td><%= "#{credit.apellido_paterno} #{credit.apellido_materno} #{credit.nombre_1} #{credit.nombre_2}" %></td>
        <td><%= credit.RFC %></td>
        <td><%= Dinero.to_money(credit.monto_solicitud) %></td>
        <td><%= credit.created_at.strftime("%d/%m/%Y") %></br> <%= credit.created_at.strftime("%H:%m") %> </td>
        <td><%= link_to 'Mostrar',credit,class:'crud-links' %></td>
        <td><%= link_to 'Editar', edit_credit_path(credit),class:'crud-links' %></td>
        <% if current_user.tipo == 1%>
          <td><%=link_to  'Aceptar', credit_path(credit,:credit=>{status:1}), :method=> :put,class:"waves-effect waves-light btn"%></td>
          <td><%=link_to  'Rechazar', credit_path(credit,:credit=>{status:2}), :method=> :put,class:"waves-effect waves-light btn"%></td>
        <% end %>
        <td><%=link_to  'ver PDFS',pdf_path(credit),target:"_blank", class:"waves-effect waves-light btn"%></td>
      </tr>
      
    <% end %>
  </tbody>
</table>

<br>

app/views/view_credits/rechazadas.html.erb
<p id="notice"><%= notice %></p>

<h1 align="center">SOLICITUDES RECHAZADAS</h1>
<style>
  td{
    padding:5px 5px; 
  }
  </style>
<table style="font-size:12px;">
  <thead>
    <tr>
      <th>AGENTE/EMPRESA</th>

      <th>FECHA</th>
      <th>NOMBRE</th>
      <th>RFC</th>
      <th>MONTO</th>
      
      <th colspan="1"></th>
    </tr>
  </thead>

  <tbody>
    <% @credits.each do |credit| %>
      <tr>
        <td><%= credit.padre.nombre_completo %></td>
        <td><%= credit.fecha.strftime("%d/%m/%Y") %></td>
        <td><h10><%= "#{credit.apellido_paterno} #{credit.apellido_materno} #{credit.nombre_1} #{credit.nombre_2}" %></h10></td>
        <td><h10><%= credit.RFC %></h10></td>
        <td><h10><%= credit.monto_solicitud %></h10></td>
        <td><h10><%= link_to 'Mostrar',credit,class:'crud-links' %></h10></td>
      </tr>
      
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'Nueva solicitud', new_credit_path, class:"crud-links" %>

app/views/view_credits/show.html.erb
<div class="row card-panel deep-orange lighten-1">  
  <h5 class="center-align ">
    <strong>Credito</strong>
   
  </h5>
  </div>
  <div class="show row">
<p>
  <strong>Agente empresa:</strong>
  <%= @credit.agente_empresa %>
</p>

<p>
  <strong>Referencia agenteempresa:</strong>
  <%= @credit.referencia_agente_empresa %>
</p>

<p>
  <strong>Fecha:</strong>
  <%= @credit.fecha %>
</p>

<p>
  <strong>Es cliente:</strong>
  <%= @credit.es_cliente %>
</p>

<p>
  <strong>Como se entero:</strong>
  <%= @credit.como_se_entero %>
</p>

<p>
  <strong>Familiar con prestamo:</strong>
  <%= @credit.familiar_con_prestamo %>
</p>

<p>
  <strong>Nombre completo familiar 1:</strong>
  <%= @credit.nombre_completo_familiar_1 %>
</p>

<p>
  <strong>Parentesco 1:</strong>
  <%= @credit.parentesco_1 %>
</p>

<p>
  <strong>Nombre completo familiar 1:</strong>
  <%= @credit.nombre_completo_familiar_1 %>
</p>



<p>
  <strong>Nombre completo familiar 1:</strong>
  <%= @credit.nombre_completo_familiar_1 %>
</p>

<p>
  <strong>Parentesco 1:</strong>
  <%= @credit.parentesco_1 %>
</p>

<p>
  <strong>Apellido paterno:</strong>
  <%= @credit.apellido_paterno %>
</p>

<p>
  <strong>Apellido materno:</strong>
  <%= @credit.apellido_materno %>
</p>

<p>
  <strong>Nombre 1:</strong>
  <%= @credit.nombre_1 %>
</p>

<p>
  <strong>Nombre 2:</strong>
  <%= @credit.nombre_2 %>
</p>

<p>
  <strong>Rfc:</strong>
  <%= @credit.RFC %>
</p>

<p>
  <strong>Curp:</strong>
  <%= @credit.CURP %>
</p>

<p>
  <strong>Seguro:</strong>
  <%= @credit.seguro %>
</p>

<p>
  <strong>Ine:</strong>
  <%= @credit.INE %>
</p>

<p>
  <strong>Nacionalidad:</strong>
  <%= @credit.nacionalidad %>
</p>

<p>
  <strong>Fecha de nacimiento:</strong>
  <%= @credit.fecha_de_nacimiento %>
</p>

<p>
  <strong>Ciudad de nacimiento:</strong>
  <%= @credit.ciudad_de_nacimiento %>
</p>

<p>
  <strong>Estado de nacimiento:</strong>
  <%= @credit.estado_de_nacimiento %>
</p>



<p>
  <strong>Sexo:</strong>
  <%= @credit.sexo %>
</p>

<p>
  <strong>Telefono de casa:</strong>
  <%= @credit.telefono_de_casa %>
</p>

<p>
  <strong>Telefono celular:</strong>
  <%= @credit.telefono_celular %>
</p>

<p>
  <strong>Email 1:</strong>
  <%= @credit.email_1 %>
</p>

<p>
  <strong>Email 2:</strong>
  <%= @credit.email_2 %>
</p>

<p>
  <strong>Escolaridad:</strong>
  <%= @credit.escolaridad %>
</p>

<p>
  <strong>Actividad econimica:</strong>
  <%= @credit.economical_activity_id %>
</p>

<p>
  <strong>Numero de dependientes economicos:</strong>
  <%= @credit.numero_de_dependientes_economicos %>
</p>

<p>
  <strong>Gasto promedio mensual:</strong>
  <%= @credit.gasto_promedio_mensual %>
</p>

<p>
  <strong>Estado civil:</strong>
  <%= @credit.estado_civil %>
</p>

<p>
  <strong>Apellido paterno del conyuge:</strong>
  <%= @credit.apellido_paterno_del_conyuge %>
</p>

<p>
  <strong>Apellido materno del conyuge:</strong>
  <%= @credit.apellido_materno_del_conyuge %>
</p>

<p>
  <strong>Nombre 1 del conyuge:</strong>
  <%= @credit.nombre_1_del_conyuge %>
</p>

<p>
  <strong>Nombre 2 del conyuge:</strong>
  <%= @credit.nombre_2_del_conyuge %>
</p>

<p>
  <strong>Telefono celular del conyuge:</strong>
  <%= @credit.telefono_celular_del_conyuge %>
</p>

<p>
  <strong>Telefono de oficina del conyuge:</strong>
  <%= @credit.telefono_de_oficina_del_conyuge %>
</p>

<p>
  <strong>Fecha de nacimiento:</strong>
  <%= @credit.fecha_de_nacimiento %>
</p>

<p>
  <strong>Calle:</strong>
  <%= @credit.calle %>
</p>

<p>
  <strong>Numero interior:</strong>
  <%= @credit.numero_interior %>
</p>

<p>
  <strong>Numero exterior:</strong>
  <%= @credit.numero_exterior %>
</p>

<p>
  <strong>Tipo de domicilio:</strong>
  <%= @credit.tipo_de_domicilio %>
</p>

<p>
  <strong>Codigo postal:</strong>
  <%= @credit.codigo_postal %>
</p>

<p>
  <strong>Colonia:</strong>
  <%= @credit.colonia %>
</p>

<p>
  <strong>Localidad:</strong>
  <%= @credit.localidad %>
</p>

<p>
  <strong>Municipio:</strong>
  <%= @credit.municipio %>
</p>

<p>
  <strong>Estado actual:</strong>
  <%= @credit.estado_actual %>
</p>

<p>
  <strong>Antiguedad en el domicilio actual:</strong>
  <%= @credit.antiguedad_en_el_domicilio_actual %>
</p>

<p>
  <strong>Antiguedad en el domicilio anterior:</strong>
  <%= @credit.antiguedad_en_el_domicilio_anterior %>
</p>

<p>
  <strong>Empresa donde labora:</strong>
  <%= @credit.empresa_donde_labora %>
</p>

<p>
  <strong>Giro de la empresa:</strong>
  <%= @credit.giro_de_la_empresa %>
</p>

<p>
  <strong>Puesto:</strong>
  <%= @credit.puesto %>
</p>

<p>
  <strong>Telefono empresa:</strong>
  <%= @credit.telefono_empresa %>
</p>

<p>
  <strong>Antiguedad laboral:</strong>
  <%= @credit.antiguedad_laboral %>
</p>

<p>
  <strong>Sueldo mensual neto:</strong>
  <%= @credit.sueldo_mensual_neto %>
</p>

<p>
  <strong>Dirreccion empresa:</strong>
  <%= @credit.dirreccion_empresa %>
</p>

<p>
  <strong>Colonia empresa:</strong>
  <%= @credit.colonia_empresa %>
</p>

<p>
  <strong>Municipio empresa:</strong>
  <%= @credit.municipio_empresa %>
</p>

<p>
  <strong>Monto solicitud:</strong>
  <%= @credit.monto_solicitud %>
</p>

<p>
  <strong>Cada cuanto se realizara el pago:</strong>
  <%= @credit.cada_cuanto_se_realizara_el_pago %>
</p>

<p>
  <strong>Lugar donde se realizara el pago:</strong>
  <%= @credit.lugar_donde_se_realizara_el_pago %>
</p>

<p>
  <strong>Nombre referencia 1:</strong>
  <%= @credit.nombre_referencia_1 %>
</p>

<p>
  <strong>Domicilio referencia 1:</strong>
  <%= @credit.domicilio_referencia_1 %>
</p>

<p>
  <strong>Telefono fijo referencia 1:</strong>
  <%= @credit.telefono_fijo_referencia_1 %>
</p>

<p>
  <strong>Telefono celular referencia 1:</strong>
  <%= @credit.telefono_celular_referencia_1 %>
</p>

<p>
  <strong>Nombre referencia 2:</strong>
  <%= @credit.nombre_referencia_2 %>
</p>

<p>
  <strong>Domicilio referencia 2:</strong>
  <%= @credit.domicilio_referencia_2 %>
</p>

<p>
  <strong>Telefono fijo referencia 2:</strong>
  <%= @credit.telefono_fijo_referencia_2 %>
</p>

<p>
  <strong>Telefono celular referencia 2:</strong>
  <%= @credit.telefono_celular_referencia_2 %>
</p>

<p>
  <strong>Nombre referencia familiar:</strong>
  <%= @credit.nombre_referencia_familiar %>
</p>

<p>
  <strong>Domicilio referencia familiar:</strong>
  <%= @credit.domicilio_referencia_familiar %>
</p>

<p>
  <strong>Telefono fijo referencia familiar:</strong>
  <%= @credit.telefono_fijo_referencia_familiar %>
</p>

<p>
  <strong>Telefono celular referencia familiar:</strong>
  <%= @credit.telefono_celular_referencia_familiar %>
</p>
</div>

<%= link_to 'EDITAR', edit_credit_path(@credit),class:"waves-effect waves-light btn" %> |

<%= link_to 'ATRAS', view_credits_path,class:"waves-effect waves-light btn" %>