config/routes.rb
Rails.application.routes.draw do
  get 'ver_video/index'

  get 'codigo_postal/:cp', to: 'codigo_postal#index'
  get 'credits/nuevo', to:'credits#nuevo' 

  get 'combos/pais'

  get 'combos/estado'

  get 'combos/ciudad'
  get 'customers/:id/historial',to:'customers#historial',as:'customer_historial'
  get 'reports/seguimiento'
  get 'reports/clientes'
  get 'reports/historial_de_recibos'
  get 'reports/seguimiento_quincenal'
  get 'reports/num_tablero'
  get 'reports/vencidos'
  get 'reports/cobranza'
  get 'reports/pronostico_de_cobranza'
  get 'reports/reporte_de_pagos'
  get 'reports/estado_de_cuenta'
  get 'reports/calificaciones'
  get 'reports/historial_de_pagos'
  get 'reports/usuarios'
  get 'reports/agentes'
  get 'reports/dtkta'
  get 'reports/dtkta_cuentas'
  get 'reports/dtkta_perfil'
  get 'reports/dtkta_movtos'
  get 'multiprint',to:"tickets#multiprint" ,as: "multiprint"
  put 'cancelar/:id', to:'tickets#cancelar', as: "cancelar"
  get 'reports/consulta_creditos'

  post 'credit/cancelar/:id', to: 'credits#cancelar', as: "cancelar_credito"
  resources :tickets
  resources :destinations
  resources :payments
  get 'payments/:id/vencer', to:'payments#vencer' 
  get 'payments/:id/pagar', to:'payments#pagar'
  get 'paymentscompany', to:'payments#paymentscompany', as:'paymentscompany'
  resources :receipts

  get 'receipts/crear'

  get 'receipts/baja'
  get '/pdf/:id', to: 'credits#pdf', as: 'pdf'
  get '/text/:id', to: 'credits#text', as: 'text'
  resources :confs , except:[:new,:create,:index,:delete]
  get 'test/t21'
  get 'view_credits/documentos',to:'view_credits#documentos'
  get 'view_credits/autorizacion',to:'view_credits#autorizacion'
  get 'view_credits/caratula',to:'view_credits#caratula'
  get 'view_credits/disposiciones',to:'view_credits#disposiciones'
  get 'view_credits/caratulamun',to:'view_credits#caratulamun'
  get 'view_credits/corrida',to:'view_credits#corrida'
  get 'view_credits/corridamun',to:'view_credits#corridamun'
  get 'view_credits/contrato',to:'view_credits#contrato'
  get 'view_credits/contratomunicipal',to:'view_credits#contratomunicipal'
  get 'view_credits/entrevista',to:'view_credits#entrevista'
  get 'view_credits/poliza',to:'view_credits#poliza'
  get 'view_credits/polizamun',to:'view_credits#polizamun'
  
  get 'view_credits',to:'view_credits#index',as:'view_credits'
  get 'view_credits/aceptadas',to:'view_credits#aceptadas',as:'view_credits_aceptadas'
  get 'view_credits/rechazadas',to:'view_credits#rechazadas',as:'view_credits_rechazadas'
  resources :view_credits
  
  resources :customers
  get 'credits/:id/editpdf', to:'credits#editpdf',as:'editpdf'
  get 'view_credits/:id/pagos', to:'view_credits#pagos',as:'creditpagos'
  resources :credits
  resources :payouts
  resources :loans
  resources :products
  devise_for :users
  resources :agents
  resources :companies
  resources :branch_offices
  resources :users
  get 'perfil',to:'users#perfil',as:'perfil'
  get 'users/edit_pass/:id',to:'users#edit_pass', as: "edit_pass"
   post 'users/create2',to:'users#create2'
  
  devise_for :models
  get 'welcome/hola'

  

  root 'welcome#hola'

end

app/models/credit.rb
class Credit < ActiveRecord::Base
    belongs_to :economical_activity
    belongs_to :customer
    belongs_to :product
    belongs_to :ocupation
    has_many :pdfs
    has_many :payments
    has_many :seguimientos
    belongs_to :destination
    belongs_to :profecion
    belongs_to :ocupation
    validates :referencia_agente_empresa,
    :fecha,
    :apellido_paterno,
    :apellido_materno,
    :nombre_1,
    :nombre_2,
    :RFC,
    :CURP,
    :INE,
    :nacionalidad,
    :fecha_de_nacimiento,
    :ciudad_de_nacimiento,
    :estado_de_nacimiento,
    :telefono_de_casa,
    :telefono_celular,
    :email_1,
    :escolaridad,
    :numero_de_dependientes_economicos,
    :gasto_promedio_mensual,
    :estado_civil,
    :calle,
    :numero_exterior,
    :tipo_de_domicilio,
    #:codigo_postal,
    #:colonia,
    #:municipio,
    :empresa_donde_labora,
    :giro_de_la_empresa,
    :telefono_empresa,
    :sueldo_mensual_neto,
    :dirreccion_empresa,
    :colonia_empresa,
    :municipio_empresa,
    :monto_solicitud,
    :cada_cuanto_se_realizara_el_pago,
    :lugar_donde_se_realizara_el_pago,
    :nombre_referencia_1,
    :domicilio_referencia_1,
    :antiguedad_laboral_anos,
    :antiguedad_laboral_meses,
    :nombre_referencia_2,
    :domicilio_referencia_2,
    :country,
    :nombre_referencia_familiar,
    :domicilio_referencia_familiar,
    :economical_activity_id,
    #:estado_actual,
    #:localidad,
    :product_id,
    :destination_id,
    :customer_id,
    :profecion_id,
    presence: true
    before_save :default_values
    after_save :pdf_trans
    def pdf_trans
        Pdf.migrate_from_credits
    end
    def default_values
      self.status ||= 0
    end
    validates :status, :inclusion => {:in => [nil,0,1,2,3]}
    # 0 por aceptar
    # 1 aceptado
    # 2 rechazada
    # 3 finalizada
    validates :sexo,
    :inclusion => { :in => [nil,1, 0] }
    validates :sexo,
    :presence => { :if => 'sexo.nil?' }

    validates :fiel,
    :inclusion => { :in => [nil,1, 0] }
    validates :fiel,
    :presence => { :if => 'fiel.nil?' }
    
    validates :es_cliente,
    :inclusion => { :in => [nil,1, 0] }
    validates :es_cliente,
    :presence => { :if => 'es_cliente.nil?' }
    
    validates :familiar_con_prestamo,
    :inclusion => { :in => [nil,1, 0] }
    validates :familiar_con_prestamo,
    :presence => { :if => 'familiar_con_prestamo.nil?' }
    validates_format_of :RFC, :with => /([A-Z][A-Z]|[A-Z])[A-Z][A-Z]\d\d\d\d\d\d(\w\w\w|)/
    #eee555555eee
     validates_format_of :CURP, :with => /[A-Z][A-Z][A-Z][A-Z]\d\d\d\d\d\d[A-Z][A-Z][A-Z][A-Z][A-Z][A-Z]\w\w/
     #BEML920313HCMLNS09.
     validates :referencia_agente_empresa, numericality: { other_than: 0 }
     validates :agente_empresa,
    :inclusion => { :in => [nil,1, 0] }
    # 0 company 
    # 1 agent
    validates :agente_empresa,
    :presence => { :if => 'agente_empresa.nil?' }
    #   estado civil 
    # 0  ---  soltero   
    # 1 ----- casado
    # 2...... divorciado
    # 3-.-.-.-union libre
    # 4,-,--,-,viudo
    def estado_civil_cadena
        return case self.estado_civil
            when 0 
                "Soltero"
            when 1
                "Casado"
            when 2
                "Divorciado"
            when 3
                "Union libre"
            else
                "Viudo"
                
        end
                
    end
    def fecha_en_español
        fecha_aux = fecha_de_contrato
        cad ="#{fecha_aux.day} de "
        case fecha_aux.month  
        when 1
            cad = cad + "Enero"
        when 2
            cad = cad + "Febrero"
        when 3
            cad = cad + "Marzo"
        when 4
            cad = cad + "Abril"
        when 5
            cad = cad + "Mayo"
        when 6
            cad = cad + "Junio"
        when 7
            cad = cad + "Julio"
        when 8
            cad = cad + "agosto"
        when 9
            cad = cad + "Septiembre"
        when 10
            cad = cad + "Octubre"
        when 11
            cad = cad + "Noviembre"
        when 12
            cad = cad + "Diciembre"
        else
            cad = cad + "mes invalido"
        end
        cad = cad + " del #{fecha_aux.year}"
    end
    
    def padre 
        if agente_empresa==1
          return  Agent.find(self.referencia_agente_empresa)
        else
          return  Company.find(self.referencia_agente_empresa)
        end
    end
    def tipo_padre
        if agente_empresa==1
            "Agente"
        elsif agente_empresa == 0
            "Empresa"
        end
    end 

    def ciudad_tribunal
       xsuc= (self.padre.branch_office_id)
       return  BranchOffice.find(xsuc).ciudad_tribunal
    end

    def taza_ord
       xsuc= (self.padre.branch_office_id)
       if xsuc==36
            return  45.to_f
       else
            return  self.product.taza_de_interes_ordinaria.to_f
        end
       
    end

    def cat_sin_iva
       xsuc= (self.padre.branch_office_id)
       if xsuc==36
            return  (327.2).to_f
       else
            return  self.product.cat_sin_iva.to_f
        end
       
    end
    # agente   === 1
    # empresa === 0
    def nombre_completo_deudor
        (self.customer.nil?)? "#{self.apellido_paterno} #{self.apellido_materno} #{self.nombre_1} #{self.nombre_2}" : "#{self.customer.apellido_paterno} #{self.customer.apellido_materno} #{self.customer.nombre_1} #{self.customer.nombre_2}" 
    end
    def domicilio
    cad = "#{self.customer.calle}, #{self.customer.numero_exterior}, "
    cad = cad + " #{self.customer.numero_interior} " unless self.customer.numero_interior.nil?
    cad =cad +"#{self.customer.colonia}, #{self.customer.codigo_postal}"
  end
  def getCorrida 
        total= self.monto_solicitud.to_f + self.monto_solicitud.to_f * (self.product.taza_de_interes_ordinaria/100)
        pago = total/self.product.numero_de_pagos_a_realizar
        capital = pago/(1 + (self.product.taza_de_interes_ordinaria / 100))
        interes = (capital * ( self.product.taza_de_interes_ordinaria / 100))/ (1+ ((self.product.taza_de_interes_ordinaria - self.product.cat_sin_iva)/ 100))
        iva = interes*(self.product.taza_de_interes_ordinaria - self.product.cat_sin_iva)/100
        fecha = self.fecha
        arreglo = []
        arreglo.push(["PERIODO", "FECHA DE PAGO", "SALDO INICIAL", "CAPITAL", "INTERES", "IVA DE INTERES", "PAGO TOTAL", "SALDO FINAL"])
        self.product.numero_de_pagos_a_realizar.times do |n|
            arreglo.push([ "#{n+1}","#{(n%2==1)? fecha=fecha+15.day : fecha=fecha.end_of_month}","$#{(total-((n)*pago)).round(2)}","$#{capital.round(2)}","$#{interes.round(2)}","$#{iva.round(2)}","$#{pago.round(2)}","$#{((total-((n)*pago))-pago).round(2)}"])
        end
    arreglo
    end
     def self.get_by_branch_office(datos,suc_id)
        cad = ""
        co = 0
        datos.each do |credit| 
            if credit.padre.branch_office.id==suc_id.id
              cad = cad + " OR " unless co==0
              cad = cad + "credits.id = #{credit.id}"
              co=co+1
            end
        end
        return  (cad == "")? [] : Credit.where(cad) 
    end
    def fecha_de_contrato_formato
        aux= nil
        aux = self.fecha_de_contrato.strftime("%d/%m/%Y") unless self.fecha_de_contrato.nil?
        return aux
    end
    def calificacion
        count = 0
        self.payments.each do |payment|
            next if payment.interes == 0
            count = count + payment.vencimientos unless payment.vencimientos.nil?
        end
        if (count == 0)
            "A"
        elsif (count == 1 or count ==2)
            "B"
        elsif (count ==3 or count ==4)
            "C"
        elsif (count ==5 or count ==6)
            "D"
        elsif (count ==7 or count >7)
            "E"
        end
    end
    def periodo
        a = []
        unless self.payments == []
            a << self.payments.select(:fecha_de_pago).order(:fecha_de_pago)[0].fecha_de_pago
            a << self.payments.select(:fecha_de_pago).order(:fecha_de_pago).last.fecha_de_pago
        end
        return a 
    end
    def capital_pagado
        #self.total_pagado - self.interes_pagado
        aux = 0
        Ticket.joins(:payment=>:credit).where("credits.id = ? and tickets.status = 0",self.id).each do |ticket|
            aux += ticket.pago_capital
        end
        return aux
    end
    def total_pagado
         Ticket.joins(:payment=>:credit).where("credits.id = ? and tickets.status = 0",self.id).sum(:cantidad)
    end
    def interes_pagado
        (self.capital_pagado*(self.product.taza_de_interes_ordinaria/100))
    end
    def total_vencido
        sum = 0
        payments = Payment.joins(:credit).where("credits.id  = ? and payments.estatus = 1", self.id)
        payments.each do |payment|
            sum = sum + payment.deuda_sin_interes
        end
        return sum 
    end
    def total_vencido_con_moratorio
        sum = 0
        payments = Payment.joins(:credit).where("credits.id  = ? and payments.estatus = 1", self.id)
        payments.each do |payment|
            sum = sum + payment.deuda_con_interes
        end
        return sum 
    end
    def capital_vencido
        self.total_vencido - self.interes_vencido
    end
    def interes_vencido
       self.total_vencido * (self.product.taza_de_interes_ordinaria/100)
    end
    def interes_moratorio
        self.total_vencido_con_moratorio - self.total_vencido
    end
    def saldo_actual 
        (self.monto_solicitud * (1+(self.product.taza_de_interes_ordinaria/100))) - self.total_pagado
    end
    def atrasado
        #pagos = self.payments.where("payments.fecha_de_pago = ?","31/08/2017".to_date)
        #deuda = pagos.sum(:importe) + pagos.sum(:interes)
        #tickets=pagos.joins(:tickets)
    end
    def pdf64
        pdf = self.pdfs.order(:created_at)
        if pdf.empty?
            return ""
        else
            return pdf.last.pdf64
        end
    end
    def terminado

app/helpers/credits_helper.rb
module CreditsHelper
end

app/views/credits/edit.html.erb
<h1 align="center">Editar Credito</h1>

<%= render 'form2' %>

<%= link_to 'Show', @credit %> |
<%= link_to 'Atras', credits_path %>

app/views/credits/editpdf.html.erb
<div ng-controller="solicitud">
  
<%= form_for @credit,class:"father" do |f| %>
      
    <% if @credit.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(@credit.errors.count, "error") %> prohibited this credit from being saved:</h2>
  
        <ul>
        <% @credit.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
        </ul>
      </div>
    <% end %>
      
    
    <div class="actions" id="">
      <div class="input-field col s12">
         <div class="field">
            <%= f.label :pdf64,"cargar PDF" %><br>
            <input type="file" id="filePicker" onchange="previewFile()" accept=".pdf" max-size=20480>
            <input id="base64textarea" type='hidden' name="credit[pdf64]" cols="50" rows="15">
          </div>
          <script>
            var cacas = "";
             function previewFile() {
             $("#submitid").prop('disabled', true);
            var preview = $('#base64textarea');
            var file    = document.querySelector('input[type=file]').files[0];
            var reader  = new FileReader();
            
            reader.onloadend = function () {
              $("#submitid").prop('disabled', true);
              preview.val(reader.result);
              $("#submitid").prop('disabled', false);
            }
          
            if (file) {
              reader.readAsDataURL(file);
            } else {
              preview.src = "";
            }
          }
        </script>
      </div>
      <%= f.submit "Guardar",id:"submitid" %>
    </div>
  <% end %>
      <a href="/customers/<%=@credit.customer.id%>/historial">Atras</a>
</div>  

app/views/credits/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Solicitudes de credito</h1>

<table>
  <thead>
    <tr>
      <th>Agente empresa</th>
      <th>Empresa</th>
      <th>Fecha</th>
      <th>Nombre</th>
      <th>Rfc</th>
      <th>Monto</th>
      
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @credits.each do |credit| %>
      <tr>
        <td><%= credit.agente_empresa %></td>
        <td><%= credit.referencia_agente_empresa %></td>
        <td><%= credit.fecha %></td>
        <td><%= "#{credit.apellido_paterno} #{credit.apellido_materno} #{credit.nombre_1} #{credit.nombre_2}" %></td>
        <td><%= credit.RFC %></td>
         <td><%= credit.monto_solicitud %></td>
        <td><%= link_to 'Mostrar', credit,class:'crud-links' %></td>
        <td><%= link_to 'Editar', edit_credit_path(credit),class:'crud-links' %></td>
        <td><%= link_to 'Eliminar', credit, method: :delete, data: { confirm: 'Are you sure?' },class:'crud-links' %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>
<div class="fixed-action-btn" style="bottom: 45px; right: 24px;">
  <%= link_to new_credit_path,class:"btn-floating btn-large red" do  %>    
    <i class="large material-icons">add</i>
  <%end%>
</div>

app/views/credits/new.html.erb
<h1>Solicitud de credito</h1>

<%= render 'form2' %>

app/views/credits/nuevo.html.erb
<h1>Solicitud de </h1>

<%= render 'formvale' %>

app/views/credits/show.html.erb
<!--
<p id="notice"><%= notice %></p>

<p>
  <strong>Agente empresa:</strong>
  <%= @credit.agente_empresa %>
</p>

<p>
  <strong>Referencia agenteempresa:</strong>
  <%= @credit.referencia_agente_empresa %>
</p>

<p>
  <strong>Fecha:</strong>
  <%= @credit.fecha %>
</p>

<p>
  <strong>Es cliente:</strong>
  <%= @credit.es_cliente %>
</p>

<p>
  <strong>Como se entero:</strong>
  <%= @credit.como_se_entero %>
</p>

<p>
  <strong>Familiar con prestamo:</strong>
  <%= @credit.familiar_con_prestamo %>
</p>

<p>
  <strong>Nombre completo familiar 1:</strong>
  <%= @credit.nombre_completo_familiar_1 %>
</p>

<p>
  <strong>Parentesco 1:</strong>
  <%= @credit.parentesco_1 %>
</p>

<p>
  <strong>Nombre completo familiar 1:</strong>
  <%= @credit.nombre_completo_familiar_1 %>
</p>

<p>
  <strong>Nombre completo familiar 1:</strong>
  <%= @credit.nombre_completo_familiar_1 %>
</p>

<p>
  <strong>Parentesco 1:</strong>
  <%= @credit.parentesco_1 %>
</p>

<p>
  <strong>Apellido paterno:</strong>
  <%= @credit.apellido_paterno %>
</p>

<p>
  <strong>Apellido materno:</strong>
  <%= @credit.apellido_materno %>
</p>

<p>
  <strong>Nombre 1:</strong>
  <%= @credit.nombre_1 %>
</p>

<p>
  <strong>Nombre 2:</strong>
  <%= @credit.nombre_2 %>
</p>

<p>
  <strong>Rfc:</strong>
  <%= @credit.RFC %>
</p>

<p>
  <strong>Curp:</strong>
  <%= @credit.CURP %>
</p>

<p>
  <strong>Seguro:</strong>
  <%= @credit.seguro %>
</p>

<p>
  <strong>Ine:</strong>
  <%= @credit.INE %>
</p>

<p>
  <strong>fiel:</strong>
  <%= @credit.fiel %>
</p>

<p>
  <strong>Nacionalidad:</strong>
  <%= @credit.nacionalidad %>
</p>

<p>
  <strong>Fecha de nacimiento:</strong>
  <%= @credit.fecha_de_nacimiento %>
</p>

<p>
  <strong>Ciudad de nacimiento:</strong>
  <%= @credit.ciudad_de_nacimiento %>
</p>

<p>
  <strong>Estado de nacimiento:</strong>
  <%= @credit.estado_de_nacimiento %>
</p>



<p>
  <strong>Sexo:</strong>
  <%= @credit.sexo %>
</p>

<p>
  <strong>Telefono de casa:</strong>
  <%= @credit.telefono_de_casa %>
</p>

<p>
  <strong>Telefono celular:</strong>
  <%= @credit.telefono_celular %>
</p>

<p>
  <strong>Email 1:</strong>
  <%= @credit.email_1 %>
</p>

<p>
  <strong>Email 2:</strong>
  <%= @credit.email_2 %>
</p>

<p>
  <strong>Escolaridad:</strong>
  <%= @credit.escolaridad %>
</p>

<p>
  <strong>Actividad econimica:</strong>
  <%= @credit.economical_activity_id %>
</p>

<p>
  <strong>Numero de dependientes economicos:</strong>
  <%= @credit.numero_de_dependientes_economicos %>
</p>

<p>
  <strong>Gasto promedio mensual:</strong>
  <%= @credit.gasto_promedio_mensual %>
</p>

<p>
  <strong>Estado civil:</strong>
  <%= @credit.estado_civil %>
</p>

<p>
  <strong>Apellido paterno del conyuge:</strong>
  <%= @credit.apellido_paterno_del_conyuge %>
</p>

<p>
  <strong>Apellido materno del conyuge:</strong>
  <%= @credit.apellido_materno_del_conyuge %>
</p>

<p>
  <strong>Nombre 1 del conyuge:</strong>
  <%= @credit.nombre_1_del_conyuge %>
</p>

<p>
  <strong>Nombre 2 del conyuge:</strong>
  <%= @credit.nombre_2_del_conyuge %>
</p>

<p>
  <strong>Telefono celular del conyuge:</strong>
  <%= @credit.telefono_celular_del_conyuge %>
</p>

<p>
  <strong>Telefono de oficina del conyuge:</strong>
  <%= @credit.telefono_de_oficina_del_conyuge %>
</p>

<p>
  <strong>Fecha de nacimiento:</strong>
  <%= @credit.fecha_de_nacimiento %>
</p>

<p>
  <strong>Calle:</strong>
  <%= @credit.calle %>
</p>

<p>
  <strong>Numero interior:</strong>
  <%= @credit.numero_interior %>
</p>

<p>
  <strong>Numero exterior:</strong>
  <%= @credit.numero_exterior %>
</p>

<p>
  <strong>Tipo de domicilio:</strong>
  <%= @credit.tipo_de_domicilio %>
</p>

<p>
  <strong>Codigo postal:</strong>
  <%= @credit.codigo_postal %>
</p>

<p>
  <strong>Colonia:</strong>
  <%= @credit.colonia %>
</p>

<p>
  <strong>Localidad:</strong>
  <%= @credit.localidad %>
</p>

<p>
  <strong>Municipio:</strong>
  <%= @credit.municipio %>
</p>

<p>
  <strong>Estado actual:</strong>
  <%= @credit.estado_actual %>
</p>

<p>
  <strong>Antiguedad en el domicilio actual:</strong>
  <%= @credit.antiguedad_en_el_domicilio_actual %>
</p>

<p>
  <strong>Antiguedad en el domicilio anterior:</strong>
  <%= @credit.antiguedad_en_el_domicilio_anterior %>
</p>

<p>
  <strong>Empresa donde labora:</strong>
  <%= @credit.empresa_donde_labora %>
</p>

<p>
  <strong>Giro de la empresa:</strong>
  <%= @credit.giro_de_la_empresa %>
</p>

<p>
  <strong>Puesto:</strong>
  <%= @credit.puesto %>
</p>

<p>
  <strong>Telefono empresa:</strong>
  <%= @credit.telefono_empresa %>
</p>


<p>
  <strong>Sueldo mensual neto:</strong>
  <%= @credit.sueldo_mensual_neto %>
</p>

<p>
  <strong>Dirreccion empresa:</strong>
  <%= @credit.dirreccion_empresa %>
</p>

<p>
  <strong>Colonia empresa:</strong>
  <%= @credit.colonia_empresa %>
</p>

<p>
  <strong>Municipio empresa:</strong>
  <%= @credit.municipio_empresa %>
</p>

<p>
  <strong>Monto solicitud:</strong>
  <%= @credit.monto_solicitud %>
</p>

<p>
  <strong>Cada cuanto se realizara el pago:</strong>
  <%= @credit.cada_cuanto_se_realizara_el_pago %>
</p>

<p>
  <strong>Lugar donde se realizara el pago:</strong>
  <%= @credit.lugar_donde_se_realizara_el_pago %>
</p>

<p>
  <strong>Nombre referencia 1:</strong>
  <%= @credit.nombre_referencia_1 %>
</p>

<p>
  <strong>Domicilio referencia 1:</strong>
  <%= @credit.domicilio_referencia_1 %>
</p>

<p>
  <strong>Telefono fijo referencia 1:</strong>
  <%= @credit.telefono_fijo_referencia_1 %>
</p>

<p>
  <strong>Telefono celular referencia 1:</strong>
  <%= @credit.telefono_celular_referencia_1 %>
</p>

<p>
  <strong>Nombre referencia 2:</strong>
  <%= @credit.nombre_referencia_2 %>
</p>

<p>
  <strong>Domicilio referencia 2:</strong>
  <%= @credit.domicilio_referencia_2 %>
</p>

<p>
  <strong>Telefono fijo referencia 2:</strong>
  <%= @credit.telefono_fijo_referencia_2 %>
</p>

<p>
  <strong>Telefono celular referencia 2:</strong>
  <%= @credit.telefono_celular_referencia_2 %>
</p>

<p>
  <strong>Nombre referencia familiar:</strong>
  <%= @credit.nombre_referencia_familiar %>
</p>

<p>
  <strong>Domicilio referencia familiar:</strong>
  <%= @credit.domicilio_referencia_familiar %>
</p>

<p>
  <strong>Telefono fijo referencia familiar:</strong>
  <%= @credit.telefono_fijo_referencia_familiar %>
</p>

<p>
  <strong>Telefono celular referencia familiar:</strong>
  <%= @credit.telefono_celular_referencia_familiar %>
</p>


<%= link_to 'Edit', edit_credit_path(@credit) %> |
<%= link_to 'Back', credits_path %>
-->
<% if @credit.product_id == 10 %>
  <%= render 'formvale' %>
<% else %>
  <%= render 'form2'%> 
<% end %>
        