config/routes.rb
Rails.application.routes.draw do
  get 'ver_video/index'

  get 'codigo_postal/:cp', to: 'codigo_postal#index'
  get 'credits/nuevo', to:'credits#nuevo' 

  get 'combos/pais'

  get 'combos/estado'

  get 'combos/ciudad'
  get 'customers/:id/historial',to:'customers#historial',as:'customer_historial'
  get 'reports/seguimiento'
  get 'reports/clientes'
  get 'reports/historial_de_recibos'
  get 'reports/seguimiento_quincenal'
  get 'reports/num_tablero'
  get 'reports/vencidos'
  get 'reports/cobranza'
  get 'reports/pronostico_de_cobranza'
  get 'reports/reporte_de_pagos'
  get 'reports/estado_de_cuenta'
  get 'reports/calificaciones'
  get 'reports/historial_de_pagos'
  get 'reports/usuarios'
  get 'reports/agentes'
  get 'reports/dtkta'
  get 'reports/dtkta_cuentas'
  get 'reports/dtkta_perfil'
  get 'reports/dtkta_movtos'
  get 'multiprint',to:"tickets#multiprint" ,as: "multiprint"
  put 'cancelar/:id', to:'tickets#cancelar', as: "cancelar"
  get 'reports/consulta_creditos'

  post 'credit/cancelar/:id', to: 'credits#cancelar', as: "cancelar_credito"
  resources :tickets
  resources :destinations
  resources :payments
  get 'payments/:id/vencer', to:'payments#vencer' 
  get 'payments/:id/pagar', to:'payments#pagar'
  get 'paymentscompany', to:'payments#paymentscompany', as:'paymentscompany'
  resources :receipts

  get 'receipts/crear'

  get 'receipts/baja'
  get '/pdf/:id', to: 'credits#pdf', as: 'pdf'
  get '/text/:id', to: 'credits#text', as: 'text'
  resources :confs , except:[:new,:create,:index,:delete]
  get 'test/t21'
  get 'view_credits/documentos',to:'view_credits#documentos'
  get 'view_credits/autorizacion',to:'view_credits#autorizacion'
  get 'view_credits/caratula',to:'view_credits#caratula'
  get 'view_credits/disposiciones',to:'view_credits#disposiciones'
  get 'view_credits/caratulamun',to:'view_credits#caratulamun'
  get 'view_credits/corrida',to:'view_credits#corrida'
  get 'view_credits/corridamun',to:'view_credits#corridamun'
  get 'view_credits/contrato',to:'view_credits#contrato'
  get 'view_credits/contratomunicipal',to:'view_credits#contratomunicipal'
  get 'view_credits/entrevista',to:'view_credits#entrevista'
  get 'view_credits/poliza',to:'view_credits#poliza'
  get 'view_credits/polizamun',to:'view_credits#polizamun'
  
  get 'view_credits',to:'view_credits#index',as:'view_credits'
  get 'view_credits/aceptadas',to:'view_credits#aceptadas',as:'view_credits_aceptadas'
  get 'view_credits/rechazadas',to:'view_credits#rechazadas',as:'view_credits_rechazadas'
  resources :view_credits
  
  resources :customers
  get 'credits/:id/editpdf', to:'credits#editpdf',as:'editpdf'
  get 'view_credits/:id/pagos', to:'view_credits#pagos',as:'creditpagos'
  resources :credits
  resources :payouts
  resources :loans
  resources :products
  devise_for :users
  resources :agents
  resources :companies
  resources :branch_offices
  resources :users
  get 'perfil',to:'users#perfil',as:'perfil'
  get 'users/edit_pass/:id',to:'users#edit_pass', as: "edit_pass"
   post 'users/create2',to:'users#create2'
  
  devise_for :models
  get 'welcome/hola'

  

  root 'welcome#hola'

end

app/models/product.rb
class Product < ActiveRecord::Base
     has_many :branchOffices
     belongs_to :loan
     belongs_to :payout
     has_many :credits
     validates :nombre_del_producto,
     :registro_del_contrado_de_adhesion,
     :plazo_de_prestamo,
     :numero_de_pagos_a_realizar,
     :taza_de_interes_ordinaria,
     :taza_de_interes_moratoria,
     :cat_sin_iva,
     :plazo,
     :numero_de_meses_de_sueldo_para_prestamo,
     :loan_id,
     :payout_id,
     presence:true
     
     def fechas_de_impresion
          arr = Payment.joins(:credit=>:product).select(:fecha_de_impresion).where("products.id = ?",self.id).uniq.where("payments.fecha_de_pago < ? ",Time.now + 1.month)
            
          while (arr.last.fecha_de_impresion <= Time.now)
               arr << Payment.new(fecha_de_impresion:Auxiliar.getArreglo(self,arr.last.fecha_de_impresion)["impresion"])
          end
          arr
     end
     def fechas_de_corte
          arr = Payment.select(:fecha_de_corte).joins(:credit=>:product).where("credits.status = ? ",1 ).where("products.id = ? ", self.id).uniq.order(:fecha_de_corte)
          
          while (arr.last.fecha_de_corte <= Time.now)
               arr << Payment.new(fecha_de_corte:Auxiliar.getArreglo(self,arr.last.fecha_de_corte)["corte"])
          end
          arr
     end
     def ultimaFechaDeCorteFuncion(fecha)
           fp = Payment.select(:fecha_de_pago,:fecha_de_corte).joins(:credit=>:product).where("credits.status = ? ",1 ).where("products.id = ? ", self.id).uniq.order(:fecha_de_pago)
          while (fp.last.fecha_de_corte <= Time.now)
               fp << Payment.new(fecha_de_corte:Auxiliar.getArreglo(self,fp.last.fecha_de_corte)["corte"],fecha_de_pago:Auxiliar.getArreglo(self,fp.last.fecha_de_corte)["pago"])
          end
          fp.reverse.each do |fechas|
               return fechas if fechas.fecha_de_corte.to_date <= fecha
          end
     end
     def ultimaFechaDeCorte
         ultimaFechaDeCorteFuncion(Time.now.to_date)
     end
     def diferenciaDeCorte(fechad)
          count = 0
          fp = Payment.select(:fecha_de_pago,:fecha_de_corte).joins(:credit=>:product).where("credits.status = ? ",1 ).where("products.id = ? ", self.id).uniq.order(:fecha_de_pago)
          while (fp.last.fecha_de_corte <= Time.now)
               fp << Payment.new(fecha_de_corte:Auxiliar.getArreglo(self,fp.last.fecha_de_corte)["corte"],fecha_de_pago:Auxiliar.getArreglo(self,fp.last.fecha_de_corte)["pago"])
          end
          fp.reverse.each do |fechas|
               if fechad < fechas.fecha_de_corte.to_date and fechas.fecha_de_corte.to_date < Time.now.to_date
                    count+=1
               end
               return count if fechas.fecha_de_corte.to_date <= fechad
          end
     end
     def proximaFechaDeCorteFuncion(fecha)
          fp = Payment.select(:fecha_de_pago,:fecha_de_corte).joins(:credit=>:product).where("credits.status = ? ",1 ).where("products.id = ? ", self.id).uniq.order(:fecha_de_pago)
          while (fp.last.fecha_de_corte <= Time.now)
               fp << Payment.new(fecha_de_corte:Auxiliar.getArreglo(self,fp.last.fecha_de_corte)["corte"],fecha_de_pago:Auxiliar.getArreglo(self,fp.last.fecha_de_corte)["pago"])
          end
          fp.each do |fechas|
               return fechas if fechas.fecha_de_corte.to_date > fecha
          end
     end
     def proximaFechaDeCorte
          proximaFechaDeCorteFuncion(Time.now)
     end
     
     def rangoDeCorte(fecha_de_corte)
          ultima = ultimaFechaDeCorteFuncion(fecha_de_corte).fecha_de_corte
          proxima = proximaFechaDeCorteFuncion(fecha_de_corte)
          proxima = (proxima.kind_of?(Array))? ultima + 1.year : proxima.fecha_de_corte
          return (ultima ... proxima)
     end
     
     def modificar_seguimientos(fechainput)
          creditos = self.credits.where("status=1 or status=3").order(:apellido_paterno)
          if Auxiliar.seguimiento_guardado_contador(creditos,fechainput) > 0
               tuplas = Auxiliar.seguimiento_por_creditos_guardados(creditos,fechainput)
               tuplas.each do |t|
                    s=Seguimiento.where("credit_id= ? and fecha_corte= ?", t["credit_id"], fechainput).first
                    if s.nil?
                    else
                         s.cobrado = t["cobrado"].to_f
                         s.diferencia = t["total_a_cobrar"].to_f - t["cobrado"].to_f
                         s.adelantado = t["adelantado"].to_f
                         s.save()
                    end
               end
          end
     end
     
     
     def almacenar_seguimientos(fechainput)
          creditos = self.credits.where(status:1).order(:apellido_paterno)
          return if Auxiliar.seguimiento_guardado_contador(creditos,fechainput) > 0
          tuplas = Auxiliar.seguimiento_por_creditos(creditos, fechainput)
          tuplas.each do |t|
               Seguimiento.create(
                    nombre:t["nombre_completo"], 
                    fecha_prestamo:t["fecha"], 
                    capital:t["monto_solicitud"], 
                    monto_a_cobrar:t["monto_a_pagar"],
                    adeudo:t["adeudo"], 
                    a_pagar:t["pagar"], 
                    atrasado:t["atrasado"], 
                    interés_moratorio:t["interes_moratorio"], 
                    total_a_cobrar:t["total_a_cobrar"], 
                    cobrado:t["cobrado"], 
                    diferencia:t["diferencia"],
                    adelantado:t["adelantado"], 
                    empresa:t["empresa"],
                    no_pago:t["numero_de_pago"], 
                    no_creditos:t["numero_de_creditos"],
                    payment_id:t["payment_ref"],
                    credit_id:t["credit_id"],
                    fecha_corte:t["fecha_corte"]
               )
          end
     end
     def vencer(fecha=Time.now.to_date)
          desplazo = 0 
          desplazo = 1 if self.id == 3 or self.id == 5 or self.id == 8 or self.id == 13
          fecha = fecha - desplazo 
          if self.ultimaFechaDeCorteFuncion(fecha).fecha_de_corte == fecha
               Coman.create(c:"fecha concordo producto.id#{self.id}")
               Payment.joins(:credit).where("credits.product_id = ?",self.id)
               .where("payments.fecha_de_pago <= ?",fecha).where.not(estatus:2).each do |p|
                   p.cargar_interes
               end
               
               almacenar_seguimientos(fecha)
               
             
          end
     end
     def soloAlmacenar(fecha=Time.now.to_date)
          desplazo = 0 
          desplazo = 1 if self.id == 3 or self.id == 5 or self.id == 8
          fecha = fecha - desplazo 
          if self.ultimaFechaDeCorteFuncion(fecha).fecha_de_corte == fecha
              
               
               almacenar_seguimientos(fecha)
               
             
          end
     end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :set_product, only: [:show, :edit, :update, :destroy]

  # GET /products
  # GET /products.json
  def index
    @products = Product.all
  end

  # GET /products/1
  # GET /products/1.json
  def show
  end

  # GET /products/new
  def new
    @product = Product.new
  end

  # GET /products/1/edit
  def edit
  end

  # POST /products
  # POST /products.json
  def create
    @product = Product.new(product_params)

    respond_to do |format|
      if @product.save
        format.html { redirect_to @product, notice: 'Product was successfully created.' }
        format.json { render :show, status: :created, location: @product }
      else
        format.html { render :new }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /products/1
  # PATCH/PUT /products/1.json
  def update
    respond_to do |format|
      if @product.update(product_params)
        format.html { redirect_to @product, notice: 'Product was successfully updated.' }
        format.json { render :show, status: :ok, location: @product }
      else
        format.html { render :edit }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /products/1
  # DELETE /products/1.json
  def destroy
    @product.destroy
    respond_to do |format|
      format.html { redirect_to products_url, notice: 'Product was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_product
      @product = Product.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def product_params
      params.require(:product).permit(:etiqueta_plural, :interes_moratorio_aplicable,:plazo,:payout_id,:forma_de_pago_interes,:loan_id,:nombre_del_producto, :registro_del_contrado_de_adhesion, :plazo_de_prestamo, :numero_de_pagos_a_realizar,:plazo_de_prestamo_interes, :numero_de_pagos_a_realizar_interes, :taza_de_interes_ordinaria, :taza_de_interes_moratoria, :cat_sin_iva, :numero_de_meses_de_sueldo_para_prestamo, :comision_apert)

    end
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/products/_form.html.erb
<div ng-controller="productos">
  <div class="row">
    <%= form_for(@product) do |f| %>
      <% if @product.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(@product.errors.count, "error") %> prohibited this product from being saved:</h2>
    
          <ul>
          <% @product.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
          </ul>
        </div>
      <% end %>
    
      <div class="field">
        <%= f.label :nombre_del_producto %>
        <%= f.text_field :nombre_del_producto %>
      </div>
      <div class="field">
        <%= f.label :registro_del_contrado_de_adhesion," Registro de contrato de adhesión" %>
        <%= f.text_field :registro_del_contrado_de_adhesion %>
      </div>
      <div class="field">
        <div class="col s9 m9 l9">
          <%= f.collection_select(:loan_id, Loan.all ,:id, :nombre, :prompt => 'Tipo de préstamo:') %>
          <%=f.label :loan_id,"Tipo de prestamo"%>
        </div>
        <div class="col s3 m3 l3">
          <a href="<%=loans_path%>" target = "_blank" class="btn-floating btn-large waves-effect waves-light red"><i class="material-icons">add</i></a>
        </div>
      </div>
      <div class="field">
        
        <div class = "col s2 m2 l2">
          <a ng-click="obtenerPayouts()"  class="btn-floating btn-large waves-effect waves-light red"><i class="material-icons">replay</i></a>
        </div>
        <div class="col s7 m7 l7">
          <select id="product_payout_id" name="product[payout_id]"class="browser-default" ng-model="payouts.prepeatSelect">
            <option value="" disabled selected>Payouts</option>
            <option ng-repeat="option in payouts" value="{{option.id}}">{{option.nombre}}</option>
          </select>
         
        </div>
        <div class="col s3 m3 l3">
          <a href="<%=payouts_path%>" target = "_blank" class="btn-floating btn-large waves-effect waves-light red"><i class="material-icons">add</i></a>
        </div>
      </div>
      <div class="field">
        <%= f.label :numero_de_pagos_a_realizar,'Número de pagos a realizar capital' %>
        <%= f.number_field :numero_de_pagos_a_realizar %>
      </div>
       <div class="field">
       
        <%=f.label :plazo_de_prestamo, "Plazo de préstamo capital"%>
        <%=f.text_field :plazo_de_prestamo%>
      </div>
      
      <div class="field">
        <%= f.collection_select(:forma_de_pago_interes, Payout.all ,:id, :nombre, :prompt => 'Forma de pago:') %>
        <%=f.label :forma_de_pago_interes,"Forma de pago interés"%>
      </div>
      <div class="field">
        <%= f.label :numero_de_pagos_a_realizar_interes,'Número de pagos a realizar interés' %>
        <%= f.number_field :numero_de_pagos_a_realizar_interes %>
      </div>
       <div class="field">
        <%=f.label :plazo_de_prestamo_interes, "Plazo de préstamo interés"%>
        <%= f.text_field :plazo_de_prestamo_interes %>
      </div>
      
      <div class="field">
        <div class="col s11 m11 l11 ">
          <%= f.label :taza_de_interes_ordinaria,'Tasa de interés ordinaria' %>
          <%= f.number_field :taza_de_interes_ordinaria, :step => 'any' %>
        </div>
        <div class="col s1 m1 l1 valign-wrapper">
          <h5 class="valign">%</h5>
        </div>
      </div>
      <div class="field">
        <div class="col s11 m11 l11 ">
          <%= f.label :taza_de_interes_moratoria,'Tasa de interés moratoria' %>
          <%= f.number_field :taza_de_interes_moratoria, :step => 'any' %>
        </div>
        <div class="col s1 m1 l1 valign-wrapper">
          <h5 class="valign">%</h5>
        </div>
      </div>
      <div class="field">
        <div class="col s11 m11 l11 ">
          <%= f.label :cat_sin_iva,'CAT sin iva' %>
          <%= f.number_field :cat_sin_iva, :step => 'any' %>
        </div>
        <div class="col s1 m1 l1 valign-wrapper">
          <h5 class="valign">%</h5>
        </div>
      </div>
      <div class="field">
        <%= f.label :numero_de_meses_de_sueldo_para_prestamo,'Número de meses de sueldo para préstamo' %>
        <%= f.number_field :numero_de_meses_de_sueldo_para_prestamo %>
      </div>
      <div class="field">
        <%= f.label :plazo,'Plazo de prestamo' %>
        <%= f.text_field :plazo %>
      </div>
      <div class="field">
        <div class="col s11 m11 l11 ">
          <%= f.label :interes_moratorio_aplicable,'Interes moratorio aplicable' %>
          <%= f.number_field :interes_moratorio_aplicable, :step => 'any' %>
        </div>
        <div class="col s1 m1 l1 valign-wrapper">
          <h5 class="valign">%</h5>
        </div>
      </div>
      <div class="field">
          <%= f.label :etiqueta_plural,'Etiqueta Plural' %>
          <%= f.text_field :etiqueta_plural %>
      </div>
       <div class="field">
         <div class="col s11 m11 l11 ">
            <%= f.label :comision_apert,'Comisión por Apertura' %>
            <%= f.number_field :comision_apert, :step => 'any' %>
          </div>
          <div class="col s1 m1 l1 valign-wrapper">
          <h5 class="valign">%</h5>
        </div>
      
      </div>
  </div>
      <div class="actions">
        <%= f.submit 'Guardar' %>
      </div>
    <% end %>
</div>

app/views/products/edit.html.erb
<h1>Producto a Editar</h1>

<%= render 'form' %>

<%= link_to 'Mostrar', @product,class:"crud-links" %> |
<%= link_to 'Atras', products_path,class:"crud-links" %>

app/views/products/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Lista de Productos</h1>

<table class="responsive-table">
  <thead>
    <tr>
      <th>Nombre del producto</th>
      <th>RECA</th>
      <th>Plazo de préstamo</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @products.each do |product| %>
      <tr>
        <td><%= product.nombre_del_producto %></td>
        <td><%= product.registro_del_contrado_de_adhesion %></td>
        <td><%= product.plazo_de_prestamo %></td>
        <td><%= link_to 'Mostrar', product,class:'crud-links' %></td>
        <td><%= link_to 'Editar', edit_product_path(product),class:'crud-links' %></td>
        <td><%= link_to 'Eliminar', product, method: :delete, data: { confirm: 'Estas seguro de eliminar este producto?' },class:'crud-links' %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>
<div class="fixed-action-btn" style="bottom: 45px; right: 24px;">
  <%= link_to new_product_path,class:"btn-floating btn-large red" do  %>    
    <i class="large material-icons">add</i>
  <%end%>
</div>

app/views/products/new.html.erb
<h1>Crear Producto</h1>

<%= render 'form' %>

<%= link_to 'Atras', products_path,class:'crud-links' %>

app/views/products/show.html.erb
<div class="row card-panel deep-orange lighten-1">  
  <h5 class="center-align ">
    <strong>Nombre del producto:</strong>
    <%= @product.nombre_del_producto %>
  </h5>
</div>
<div class="show row">  
  <p>
    <strong>Registro del contrado de adhesión:</strong>
    <%= @product.registro_del_contrado_de_adhesion %>
  </p>
  
  <p>
    <strong>Plazo de préstamo:</strong>
    <%= @product.plazo_de_prestamo %>
  </p>
  
  <p>
    <strong>Numero de pagos a realizar:</strong>
    <%= @product.numero_de_pagos_a_realizar %>
  </p>
  
  <p>
    <strong>Tipo de préstamo:</strong>
    <%=@product.loan.nombre %>
  </p>
  <p>
    <strong>Forma de pago:</strong>
    <%=@product.payout.nombre %>
  </p>
  <p>
    <strong>Tasa de interés ordinaria:</strong>
    <%= @product.taza_de_interes_ordinaria %>%
  </p>
  
  <p>
    <strong>Tasa de interés moratoria:</strong>
    <%= @product.taza_de_interes_moratoria %>%
  </p>
  
  <p>
    <strong>Cat sin iva:</strong>
    <%= @product.cat_sin_iva %>%
  </p>
  
  <p>
    <strong>Numero de meses de sueldo para préstamo:</strong>
    <%= @product.numero_de_meses_de_sueldo_para_prestamo %>
  </p>
  <p>
    <strong>Plazo de prestamo:</strong>
    <%= @product.plazo %>
  </p>
  <p>
    <strong>Interés moratorio aplicable:</strong>
    <%= @product.interes_moratorio_aplicable %>%
  </p>
  
   <p>
    <strong>Comisión por Apertura:</strong>
    <%= @product.comision_apert %>%
  </p>
</div>
<%= link_to 'Editar', edit_product_path(@product),class:"crud-links" %> |
<%= link_to 'Atras', products_path,class:"crud-links" %>